/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gpinfinity.repository;

import com.gpinfinity.entities.TerComisionesTextil;
import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 *
 * @author nivrist
 */
@Repository
public interface ITerComisionesTextilRespository extends JpaRepository<TerComisionesTextil, Integer> {

    @Procedure(procedureName = "TER_COMISIONES_TEXTIL_Generar")
    public void calculaComisiones(@Param("PERIODO") int periodo);

    @Query(nativeQuery = true, value = "SELECT distinct cast(periodo as varchar) periodo_tbl FROM TER_COMISIONES_TEXTIL order by 1 asc")
    public List<String> allPeriodo();

    @Query(nativeQuery = true, value = "SELECT * FROM TER_COMISIONES_TEXTIL where periodo =?")
    public List<TerComisionesTextil> allTerComisionesTextil(int periodo);

    @Query(nativeQuery = true, value = "select TIPO_BONO , BONO,\n"
            + "cast(cast(ENERO as decimal(10,2)) as varchar) jan ,\n"
            + "cast(cast(FEBRERO as decimal(10,2)) as varchar) feb ,\n"
            + "cast(cast(MARZO as decimal(10,2)) as varchar) mar ,\n"
            + "cast(cast(ABRIL as decimal(10,2)) as varchar) apr ,\n"
            + "cast(cast(MAYO as decimal(10,2)) as varchar) may ,\n"
            + "cast(cast(JUNIO as decimal(10,2)) as varchar) jun ,\n"
            + "cast(cast(JULIO as decimal(10,2)) as varchar) jul ,\n"
            + "cast(cast(AGOSTO as decimal(10,2)) as varchar) aug ,\n"
            + "cast(cast(SEPTIEMBRE as decimal(10,2)) as varchar) sep ,\n"
            + "cast(cast(OCTUBRE as decimal(10,2)) as varchar) oct ,\n"
            + "cast(cast(NOVIEMBRE as decimal(10,2)) as varchar) nov ,\n"
            + "cast(cast(DICIEMBRE as decimal(10,2)) as varchar) dece \n"
            + "from  (\n"
            + "SELECT case SUBSTRING(cast(B.periodo as varchar),5,3) \n"
            + "	when '01' then 'ENERO' \n"
            + "	when '02' then 'FEBRERO' \n"
            + "	when '03' then 'MARZO' \n"
            + "	when '04' then 'ABRIL' \n"
            + "	when '05' then 'MAYO' \n"
            + "	when '06' then 'JUNIO' \n"
            + "	when '07' then 'JULIO' \n"
            + "	when '08' then 'AGOSTO' \n"
            + "	when '09' then 'SEPTIEMBRE' \n"
            + "	when '10' then 'OCTUBRE' \n"
            + "	when '11' then 'NOVIEMBRE' \n"
            + "	ELSE 'DICIEMBRE' end mes,\n"
            + "    A.descripcion as TIPO_BONO,\n"
            + "	A.valor as BONO\n"
            + ", ROUND((A.valor * (B.porc_cumplimiento_mensual/100))* C.valor,2) + ROUND((A.valor * (B.porc_cumplimiento_acumulado/100))*CC.valor,2) AS monto_total\n"
            + "FROM TER_TIPO_BONO_TEXTIL A\n"
            + "INNER JOIN TER_COMISIONES_TEXTIL B ON B.periodo = A.periodo\n"
            + "INNER JOIN TER_PARAM_TEXTIL C ON C.llave = 'BONIF_MES'\n"
            + "INNER JOIN TER_PARAM_TEXTIL CC ON CC.llave = 'BONIF_CUM'\n"
            + " ) x\n"
            + " PIVOT\n"
            + "( MAX(x.monto_total) FOR x.mes IN (ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE)) p\n"
            + " order by tipo_bono asc")
    public List<Object[]> textilesTotal();

    @Query(nativeQuery = true, value = "select  distinct ' ' tipo_bono_textil , 0 bono,\n"
            + "cast(cast(ENERO as decimal(10,2)) as varchar) jan ,\n"
            + "cast(cast(FEBRERO as decimal(10,2)) as varchar) feb ,\n"
            + "cast(cast(MARZO as decimal(10,2)) as varchar) mar ,\n"
            + "cast(cast(ABRIL as decimal(10,2)) as varchar) apr ,\n"
            + "cast(cast(MAYO as decimal(10,2)) as varchar) may ,\n"
            + "cast(cast(JUNIO as decimal(10,2)) as varchar) jun ,\n"
            + "cast(cast(JULIO as decimal(10,2)) as varchar) jul ,\n"
            + "cast(cast(AGOSTO as decimal(10,2)) as varchar) aug ,\n"
            + "cast(cast(SEPTIEMBRE as decimal(10,2)) as varchar) sep ,\n"
            + "cast(cast(OCTUBRE as decimal(10,2)) as varchar) oct ,\n"
            + "cast(cast(NOVIEMBRE as decimal(10,2)) as varchar) nov ,\n"
            + "cast(cast(DICIEMBRE as decimal(10,2)) as varchar) dece from  (\n"
            + "SELECT  case SUBSTRING(cast(B.periodo as varchar),5,3) \n"
            + "	when '01' then 'ENERO' \n"
            + "	when '02' then 'FEBRERO' \n"
            + "	when '03' then 'MARZO' \n"
            + "	when '04' then 'ABRIL' \n"
            + "	when '05' then 'MAYO' \n"
            + "	when '06' then 'JUNIO' \n"
            + "	when '07' then 'JULIO' \n"
            + "	when '08' then 'AGOSTO' \n"
            + "	when '09' then 'SEPTIEMBRE' \n"
            + "	when '10' then 'OCTUBRE' \n"
            + "	when '11' then 'NOVIEMBRE' \n"
            + "	ELSE 'DICIEMBRE' end mes,\n"
            + " A.descripcion as tipo_bono_textil\n"
            + ", (B.porc_cumplimiento_mensual) as porc_cumplimiento_mensual\n"
            + "FROM TER_TIPO_BONO_TEXTIL A\n"
            + "INNER JOIN TER_COMISIONES_TEXTIL B ON B.periodo = A.periodo\n"
            + "INNER JOIN TER_PARAM_TEXTIL C ON C.llave = 'BONIF_MES'\n"
            + "INNER JOIN TER_PARAM_TEXTIL CC ON CC.llave = 'BONIF_CUM'\n"
            + "\n"
            + " ) header\n"
            + " PIVOT\n"
            + "(\n"
            + "     MAX(header.porc_cumplimiento_mensual) \n"
            + "	 FOR header.mes IN (ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE)\n"
            + ") p union \n"
            + "\n"
            + "select tipo_bono_textil, BONO ,cast(cast(ENERO as decimal(10,2)) as varchar) jan ,\n"
            + "cast(cast(FEBRERO as decimal(10,2)) as varchar) feb ,\n"
            + "cast(cast(MARZO as decimal(10,2)) as varchar) mar ,\n"
            + "cast(cast(ABRIL as decimal(10,2)) as varchar) apr ,\n"
            + "cast(cast(MAYO as decimal(10,2)) as varchar) may ,\n"
            + "cast(cast(JUNIO as decimal(10,2)) as varchar) jun ,\n"
            + "cast(cast(JULIO as decimal(10,2)) as varchar) jul ,\n"
            + "cast(cast(AGOSTO as decimal(10,2)) as varchar) aug ,\n"
            + "cast(cast(SEPTIEMBRE as decimal(10,2)) as varchar) sep ,\n"
            + "cast(cast(OCTUBRE as decimal(10,2)) as varchar) oct ,\n"
            + "cast(cast(NOVIEMBRE as decimal(10,2)) as varchar) nov ,\n"
            + "cast(cast(DICIEMBRE as decimal(10,2)) as varchar) dece from  (\n"
            + "SELECT case SUBSTRING(cast(B.periodo as varchar),5,3) \n"
            + "	when '01' then 'ENERO' \n"
            + "	when '02' then 'FEBRERO' \n"
            + "	when '03' then 'MARZO' \n"
            + "	when '04' then 'ABRIL' \n"
            + "	when '05' then 'MAYO' \n"
            + "	when '06' then 'JUNIO' \n"
            + "	when '07' then 'JULIO' \n"
            + "	when '08' then 'AGOSTO' \n"
            + "	when '09' then 'SEPTIEMBRE' \n"
            + "	when '10' then 'OCTUBRE' \n"
            + "	when '11' then 'NOVIEMBRE' \n"
            + "	ELSE 'DICIEMBRE' end mes,\n"
            + " A.descripcion as tipo_bono_textil,\n"
            + " 	A.valor as BONO\n"
            + ", ROUND((A.valor * (B.porc_cumplimiento_mensual/100))* C.valor,2) AS monto_bonificacion_mensual\n"
            + "FROM TER_TIPO_BONO_TEXTIL A\n"
            + "INNER JOIN tER_COMISIONES_TEXTIL B ON B.periodo = A.periodo\n"
            + "INNER JOIN TER_PARAM_TEXTIL C ON C.llave = 'BONIF_MES'\n"
            + "INNER JOIN TER_PARAM_TEXTIL CC ON CC.llave = 'BONIF_CUM'\n"
            + "\n"
            + " ) x\n"
            + " PIVOT\n"
            + "(\n"
            + "     MAX(x.monto_bonificacion_mensual) FOR x.mes IN (ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE)\n"
            + ") p")
    public List<Object[]> textilesMensual();

    @Query(nativeQuery = true, value = "select  distinct ' ' tipo_bono_textil , 0 bono,\n"
            + "cast(cast(ENERO as decimal(10,2)) as varchar) jan ,\n"
            + "cast(cast(FEBRERO as decimal(10,2)) as varchar) feb ,\n"
            + "cast(cast(MARZO as decimal(10,2)) as varchar) mar ,\n"
            + "cast(cast(ABRIL as decimal(10,2)) as varchar) apr ,\n"
            + "cast(cast(MAYO as decimal(10,2)) as varchar) may ,\n"
            + "cast(cast(JUNIO as decimal(10,2)) as varchar) jun ,\n"
            + "cast(cast(JULIO as decimal(10,2)) as varchar) jul ,\n"
            + "cast(cast(AGOSTO as decimal(10,2)) as varchar) aug ,\n"
            + "cast(cast(SEPTIEMBRE as decimal(10,2)) as varchar) sep ,\n"
            + "cast(cast(OCTUBRE as decimal(10,2)) as varchar) oct ,\n"
            + "cast(cast(NOVIEMBRE as decimal(10,2)) as varchar) nov ,\n"
            + "cast(cast(DICIEMBRE as decimal(10,2)) as varchar) dece from  (\n"
            + "SELECT  case SUBSTRING(cast(B.periodo as varchar),5,3) \n"
            + "	when '01' then 'ENERO' \n"
            + "	when '02' then 'FEBRERO' \n"
            + "	when '03' then 'MARZO' \n"
            + "	when '04' then 'ABRIL' \n"
            + "	when '05' then 'MAYO' \n"
            + "	when '06' then 'JUNIO' \n"
            + "	when '07' then 'JULIO' \n"
            + "	when '08' then 'AGOSTO' \n"
            + "	when '09' then 'SEPTIEMBRE' \n"
            + "	when '10' then 'OCTUBRE' \n"
            + "	when '11' then 'NOVIEMBRE' \n"
            + "	ELSE 'DICIEMBRE' end mes,\n"
            + " A.descripcion as tipo_bono_textil\n"
            + ", (B.porc_cumplimiento_acumulado) as porc_cumplimiento_acumulado\n"
            + "FROM TER_TIPO_BONO_TEXTIL A\n"
            + "INNER JOIN tER_COMISIONES_TEXTIL B ON B.periodo = A.periodo\n"
            + "INNER JOIN TER_PARAM_TEXTIL C ON C.llave = 'BONIF_MES'\n"
            + "INNER JOIN TER_PARAM_TEXTIL CC ON CC.llave = 'BONIF_CUM'\n"
            + "\n"
            + " ) header\n"
            + " PIVOT\n"
            + "(\n"
            + "     MAX(header.porc_cumplimiento_acumulado) \n"
            + "	 FOR header.mes IN (ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE)\n"
            + ") p union \n"
            + "\n"
            + "select tipo_bono_textil, BONO ,cast(cast(ENERO as decimal(10,2)) as varchar) jan ,\n"
            + "cast(cast(FEBRERO as decimal(10,2)) as varchar) feb ,\n"
            + "cast(cast(MARZO as decimal(10,2)) as varchar) mar ,\n"
            + "cast(cast(ABRIL as decimal(10,2)) as varchar) apr ,\n"
            + "cast(cast(MAYO as decimal(10,2)) as varchar) may ,\n"
            + "cast(cast(JUNIO as decimal(10,2)) as varchar) jun ,\n"
            + "cast(cast(JULIO as decimal(10,2)) as varchar) jul ,\n"
            + "cast(cast(AGOSTO as decimal(10,2)) as varchar) aug ,\n"
            + "cast(cast(SEPTIEMBRE as decimal(10,2)) as varchar) sep ,\n"
            + "cast(cast(OCTUBRE as decimal(10,2)) as varchar) oct ,\n"
            + "cast(cast(NOVIEMBRE as decimal(10,2)) as varchar) nov ,\n"
            + "cast(cast(DICIEMBRE as decimal(10,2)) as varchar) dece from  (\n"
            + "SELECT case SUBSTRING(cast(B.periodo as varchar),5,3) \n"
            + "	when '01' then 'ENERO' \n"
            + "	when '02' then 'FEBRERO' \n"
            + "	when '03' then 'MARZO' \n"
            + "	when '04' then 'ABRIL' \n"
            + "	when '05' then 'MAYO' \n"
            + "	when '06' then 'JUNIO' \n"
            + "	when '07' then 'JULIO' \n"
            + "	when '08' then 'AGOSTO' \n"
            + "	when '09' then 'SEPTIEMBRE' \n"
            + "	when '10' then 'OCTUBRE' \n"
            + "	when '11' then 'NOVIEMBRE' \n"
            + "	ELSE 'DICIEMBRE' end mes,\n"
            + " A.descripcion as tipo_bono_textil,\n"
            + " 	A.valor as BONO\n"
            + ", ROUND((A.valor * (B.porc_cumplimiento_acumulado/100))* CC.valor,2) AS monto_bonificacion_acumulado\n"
            + "FROM TER_TIPO_BONO_TEXTIL A\n"
            + "INNER JOIN tER_COMISIONES_TEXTIL B ON B.periodo = A.periodo\n"
            + "INNER JOIN TER_PARAM_TEXTIL C ON C.llave = 'BONIF_MES'\n"
            + "INNER JOIN TER_PARAM_TEXTIL CC ON CC.llave = 'BONIF_CUM'\n"
            + "\n"
            + " ) x\n"
            + " PIVOT\n"
            + "(\n"
            + "     MAX(x.monto_bonificacion_acumulado) FOR x.mes IN (ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE)\n"
            + ") p")
    public List<Object[]> textilesAcumulado();

}
